---
# tasks file for mods-hadoop
- name: Install requirements
  apt: 
    name: openjdk-8-jdk
    update_cache: yes

- name: Download Spark and extract
  get_url:
    url: "https://dlcdn.apache.org/spark/spark-{{ spark_version }}.0/spark-{{ spark_version }}.0-bin-hadoop{{ spark_version }}.tgz" 
    dest: "/opt/hadoop/spark-{{ spark_version }}.0.tgz"

- name: extract and create spark dir
  become: yes
  unarchive:
    remote_src: true
    src: "/opt/hadoop/spark-{{ spark_version }}.0.tgz"
    dest: /opt/hadoop/
    list_files: yes
    mode: "0755"

- name: Rename Spark dir
  command: "mv /opt/hadoop/spark-{{ spark_version }}.0-bin-hadoop{{spark_version }} {{ spark_home }}"

- name: configure the environment
  template: 
    src: spark-env.sh.j2
    dest: "{{ spark_home }}/conf/spark-env.sh"

- name: configure spark defaults config file
  template:
    src: spark-defaults.conf.j2
    dest: "{{ spark_home }}/conf/spark-defaults.conf"

- name: Add ENV to spark .bashrc
  blockinfile:
    name: /home/hadoopuser/.bashrc
    block: |
      export SPARK_HOME=/opt/hadoop/spark 
      export PATH=$PATH:$SPARK_HOME/bin
