---
# handlers file for mods-hadoop
- name: stop hadoop
  shell: "{{ hadoop_home }}/sbin/stop-dfs.sh"
  listen: "restart hadoop"

- name: start hadoop
  shell: "{{ hadoop_home }}/sbin/start-dfs.sh"
  listen: "restart hadoop"

- name: stop YARN
  shell: "/usr/bin/nohup {{ hadoop_home }}/sbin/stop-yarn.sh"
  listen: "restart yarn"  

- name: start YARN
  shell: "/usr/bin/nohup {{ hadoop_home }}/sbin/start-yarn.sh"
  listen: "restart yarn"
