version: "3.7"
 
services:
  zookeeper:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    image: bitnami/kafka:2.7.0
    container_name: kafka1
    ports:
            - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.16.64.7:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        #command: kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 3 --partitions 4 --topic test
    depends_on:
      - zookeeper

  kafka2:
    image: bitnami/kafka:2.7.0
    container_name: kafka2
    ports:
            - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.16.64.7:9093
      - KAFKA_CFG_PORT=9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper

  kafka3:
    image: bitnami/kafka:2.7.0
    container_name: kafka3
    ports:
            - '9094:9094'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.16.64.7:9094
      - KAFKA_CFG_PORT=9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper
