---
- name: Install docker requirements 
  apt: 
    name: ca-certificates, curl, gnupg, lsb-release
    update_cache: yes 

- name: Add Docker apt key.
  apt_key:
    url: "{{ docker_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

  #- name: Add Docker apt key
  #shell: >
  #  "curl -fsSL {{ docker_gpg_key }} | sudo apt-key add -"

- name: Add docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    filename: docker
    state: present
    update_cache: true

- name: Install Docker.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "started"
    enabled: "true"

- name: Include docker-compose 
  include: docker-compose.yml
