---
# tasks file for mods-kafka
- name: Ensure that docker engine is installed
  include_role: 
    name: mods-kafka
    tasks_from: install-docker

- name: Install Distributed Kafka using docker-compose
  template:
    src: docker-compose.yml
    dest: /usr/local/src/docker-compose.yml

- name: deploy Docker compose cluster
  become: true
  shell: 
    cmd: /usr/local/bin/docker-compose up -d
    chdir: /usr/local/src/
